// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web in this project.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBbfsgurulLiw5EN4AG9tCU0LThryhwuQQ",
    authDomain: "bright-weddings-27602.firebaseapp.com",
    projectId: "bright-weddings-27602",
    storageBucket: "bright-weddings-27602.firebasestorage.app",
    messagingSenderId: "162028635060",
    appId: "1:162028635060:web:585482a99ea1f21b4a68e1",
    measurementId: "G-LC6YKPN1DX",
  );
}